AWSTemplateFormatVersion: 2010-09-09
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-033a1ebf088e56e81
      InstanceType: t2.micro
      
 Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: test-Bucket
      Tags:
       - Key: Name
         Value: production-s3bucket
